version: '3.9'
services:
    compre-scheduling-backend:
        container_name: compre-scheduling-backend
        #image: compre-scheduling-backend
        #restart: always
        command: npm start
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - webnet
        depends_on:
            - compre-scheduling-db
        working_dir: /usr/src/app
        environment:
            NODE_ENV: docker
    compre-scheduling-db:
        container_name: compre-scheduling-db
        image: postgres:12
        networks:
            - webnet
        environment:
            #here variable are used to createdefault DB for compre-scheduling
            POSTGRES_PASSWORD: eatsleepcode
            POSTGRES_USER: postgres
            POSTGRES_DB: compreschedule
            # here it'll keep al psql data of compre-scheduling
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
    webnet:
volumes:
    pgdata:
